import { ArrowLeft, ArrowRight, Box, MapPin, Navigation } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { api, errorMessage } from '../lib/api';
import type { Order } from '../types';

export function NewOrderPage() {
  const navigate = useNavigate();
  const tomorrow = new Date(Date.now() + 86_400_000); tomorrow.setMinutes(tomorrow.getMinutes() - tomorrow.getTimezoneOffset());
  const [form, setForm] = useState({ pickupAddress: 'Connaught Place, New Delhi', pickupLat: '28.6315', pickupLng: '77.2167', dropoffAddress: 'Cyber City, Gurugram', dropoffLat: '28.4950', dropoffLng: '77.0890', recipientName: '', recipientPhone: '', packageDescription: '', weightKg: '1', expectedDeliveryAt: tomorrow.toISOString().slice(0, 16) });
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const field = (name: keyof typeof form) => (event: React.ChangeEvent<HTMLInputElement>) => setForm({ ...form, [name]: event.target.value });
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const { data } = await api.post<{ order: Order }>('/orders', { pickup: { address: form.pickupAddress, lat: Number(form.pickupLat), lng: Number(form.pickupLng) }, dropoff: { address: form.dropoffAddress, lat: Number(form.dropoffLat), lng: Number(form.dropoffLng) }, recipientName: form.recipientName, recipientPhone: form.recipientPhone, packageDescription: form.packageDescription, weightKg: Number(form.weightKg), expectedDeliveryAt: new Date(form.expectedDeliveryAt).toISOString() }); navigate(`/orders/${data.order._id}`); } catch (err) { setError(errorMessage(err)); } finally { setBusy(false); } };

  return <><Link to="/orders" className="back-link"><ArrowLeft size={16} /> Back to orders</Link><header className="page-header"><div><span className="eyebrow">NEW SHIPMENT</span><h1>Create a delivery</h1><p>Add route, recipient, and package details.</p></div></header>
    <form className="create-form" onSubmit={submit}><section className="panel"><div className="panel__title"><div className="number-icon">1</div><div><h2>Route details</h2><p>Where should we pick up and deliver?</p></div></div><div className="route-form"><div className="route-form__marker"><span /><i /><MapPin /></div><div className="form-grid"><label className="full">Pickup address<input required value={form.pickupAddress} onChange={field('pickupAddress')} /></label><label>Pickup latitude<input type="number" step="any" required value={form.pickupLat} onChange={field('pickupLat')} /></label><label>Pickup longitude<input type="number" step="any" required value={form.pickupLng} onChange={field('pickupLng')} /></label><label className="full">Drop-off address<input required value={form.dropoffAddress} onChange={field('dropoffAddress')} /></label><label>Drop-off latitude<input type="number" step="any" required value={form.dropoffLat} onChange={field('dropoffLat')} /></label><label>Drop-off longitude<input type="number" step="any" required value={form.dropoffLng} onChange={field('dropoffLng')} /></label></div></div></section>
      <section className="panel"><div className="panel__title"><div className="number-icon">2</div><div><h2>Recipient</h2><p>Who is receiving this order?</p></div></div><div className="form-grid"><label>Recipient name<input required value={form.recipientName} onChange={field('recipientName')} placeholder="Full name" /></label><label>Phone number<input required value={form.recipientPhone} onChange={field('recipientPhone')} placeholder="+91 98765 43210" /></label></div></section>
      <section className="panel"><div className="panel__title"><div className="number-icon">3</div><div><h2>Package & promise</h2><p>Help the agent prepare for pickup.</p></div></div><div className="form-grid"><label><Box size={16} /> Package description<input required value={form.packageDescription} onChange={field('packageDescription')} placeholder="Electronics, documents…" /></label><label>Weight (kg)<input type="number" min="0.01" max="1000" step="0.01" required value={form.weightKg} onChange={field('weightKg')} /></label><label className="full">Expected delivery<input type="datetime-local" required value={form.expectedDeliveryAt} onChange={field('expectedDeliveryAt')} /></label></div></section>
      {error && <div className="form-error">{error}</div>}<div className="form-actions"><div><Navigation size={18} /><span>Coordinates power live map tracking.</span></div><button className="primary-button" disabled={busy}>{busy ? 'Creating…' : 'Create order'} <ArrowRight size={18} /></button></div></form></>;
}
