import { Activity, Clock3, Radio, Target } from 'lucide-react';
import { useEffect, useState } from 'react';
import { api, errorMessage } from '../lib/api';
import type { Metrics, OrderStatus } from '../types';

export function ReportsPage() {
  const [data, setData] = useState<{ metrics: Metrics; statusCounts: Partial<Record<OrderStatus, number>> } | null>(null); const [error, setError] = useState('');
  useEffect(() => { api.get('/analytics').then(({ data }) => setData(data)).catch((err) => setError(errorMessage(err))); }, []);
  const total = data?.metrics.totalOrders || 1; const statuses: OrderStatus[] = ['PLACED', 'PICKED_UP', 'IN_TRANSIT', 'DELIVERED'];
  return <><header className="page-header"><div><span className="eyebrow">PERFORMANCE</span><h1>Operations report</h1><p>Live delivery health and service-level indicators.</p></div></header>{error && <div className="form-error">{error}</div>}<section className="stats-grid"><article className="stat-card"><div className="stat-card__icon"><Target /></div><div><span>On-time rate</span><strong>{data?.metrics.onTimeRate ?? '—'}%</strong><small>Delivery promise kept</small></div></article><article className="stat-card"><div className="stat-card__icon"><Clock3 /></div><div><span>Average duration</span><strong>{data?.metrics.averageDeliveryHours ?? '—'}h</strong><small>Order to doorstep</small></div></article><article className="stat-card"><div className="stat-card__icon"><Radio /></div><div><span>Active now</span><strong>{data?.metrics.activeDeliveries ?? '—'}</strong><small>Tracked deliveries</small></div></article></section><section className="report-grid"><article className="panel"><div className="panel__title"><div><span className="eyebrow">ORDER MIX</span><h2>Lifecycle distribution</h2></div><Activity /></div><div className="bar-list">{statuses.map((status) => { const count = data?.statusCounts[status] ?? 0; return <div key={status}><div><span>{status.replace('_', ' ').toLowerCase()}</span><strong>{count}</strong></div><span className="bar-track"><i style={{ width: `${Math.max(3, count / total * 100)}%` }} /></span></div>; })}</div></article><article className="panel insight-card"><span className="eyebrow">SERVICE HEALTH</span><strong>{(data?.metrics.onTimeRate ?? 0) >= 90 ? 'Network is performing well' : 'On-time rate needs attention'}</strong><p>Use active delivery monitoring to identify stalled orders early and coordinate with assigned agents.</p><div className="score-ring" style={{ '--score': `${data?.metrics.onTimeRate ?? 0}%` } as React.CSSProperties}><span>{data?.metrics.onTimeRate ?? 0}<small>%</small></span></div></article></section></>;
}
